name: Update readme with blog posts
on: 
  schedule:
    - cron: '30 09 * * *'
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://rlevchenko.com/rss/
          readme-section: feed
          template: "- [{{ title }}]({{ link }}))"
